baseURL: "https://shubhamsb25.github.io/"
languageCode: en-us
title: Beyond the Abstractions
theme: "PaperMod"

params:
    ShowShareButtons: true
    ShowReadingTime: true
    homeInfoParams:
        Title: "Welcome"
        Content: "\"If you want to know how something works, take it apart and try to put it back together again\""
    socialIcons:
      - name: github
        url: 'https://github.com/shubhamsb25'
      - name: linkedin
        url: 'https://www.linkedin.com/in/shubhamsb25'
      - name: stackoverflow
        url: 'https://stackoverflow.com/users/7885581/shubham-singh-bhaisora'
      - name: twitter
        url: 'https://twitter.com/shubhamsb25'
      - name: RSS
        url: index.xml
    editPost:
        URL: "https://github.com/shubhamsb25/shubhamsb25.github.io/tree/master/content/"
        Text: "Suggest Changes"
        appendFilePath: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
